sudo: required

services:
  - docker

before_install:
  - gem install bundler:1.17.3
  - docker-compose up -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test